<?php
// SOME CONSTANTS HERE
DEFINE ('DB_HOST', '');
DEFINE ('DB_USER', '');
DEFINE ('DB_PASS', '');
DEFINE ('DB_NAME', '');
DEFINE ('ORIGIN', '');
DEFINE ('VERSION', '1.0');

//CONFIGURE PHP MAILER
DEFINE ('MAIL_HOST', '');
DEFINE ('MAIL_SMTP_AUTH', true);
DEFINE ('MAIL_SMTP_PORT', 465);
DEFINE ('MAIL_UNAME', '');
DEFINE ('MAIL_PASS', '');
DEFINE ('MAIL_SENDER', '');
DEFINE ('MAIL_CC', ''); //optional
DEFINE ('MAIL_BCC', ''); //optional